// 完整引入
import element3 from "element3";
import "element3/lib/theme-chalk/index.css";

// 按需引入
// import "element3/lib/theme-chalk/button.css";
// import {
  // ElRow,
  // ElCol,
  // ElContainer,
  // ElHeader,
  // ElFooter,
  // ElAside,
  // ElMain,
  // ElIcon,
  // ElButton,
  // ElLink,
  // ElRadio,
  // ElRadioButton,
  // ElRadioGroup,
  // ElCheckbox,
  // ElCheckboxButton,
  // ElCheckboxGroup,
  // ElInput,
  // ElInputNumber,
  // ElSelect,
  // ElOption,
  // ElOptionGroup,
  // ElCascader,
  // ElCascaderPanel,
  // ElSwitch,
  // ElSlider,
  // ElTimePicker,
  // ElTimeSelect,
  // ElDatePicker,
  // ElUpload,
  // ElRate,
  // ElColorPicker,
  // ElTransfer,
  // ElForm,
  // ElFormItem,
  // ElTag,
  // ElProgress,
  // ElTree,
  // ElPagination,
  // ElBadge,
  // ElAvatar,
  // ElAlert,
  // ElLoading,
  // ElMenu,
  // ElMenuItem,
  // ElSubmenu,
  // ElMenuItemGroup,
  // ElTabs,
  // ElTabPane,
  // ElBreadcrumb,
  // ElBreadcrumbItem,
  // ElPageHeader,
  // ElDropdown,
  // ElDropdownItem,
  // ElDropdownMenu,
  // ElSteps,
  // ElStep,
  // ElDialog,
  // ElTooltip,
  // ElPopover,
  // ElPopconfirm,
  // ElCard,
  // ElCarousel,
  // ElCarouselItem,
  // ElCollapse,
  // ElCollapseItem,
  // ElTimeline,
  // ElTimelineItem,
  // ElDivider,
  // ElCalendar,
  // ElImage,
  // ElBacktop,
  // ElInfiniteScroll,
  // ElDrawer,
  // ElScrollbar,
// } from "element3";

export default function (app) {
  // 完整引入
  app.use(element3)

  // 按需引入
  // app.use(ElButton);
}
